spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: musicommunity
  datasource:
    url: jdbc:mysql://${music.mysql.ip}:${music.mysql.port}/${music.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${music.mysql.username}
    password: ${music.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5                  # 最小空闲连接数
      maximum-pool-size: 15            # 最大连接数
      connection-timeout: 60000        # 连接超时时间(毫秒)
      initialization-fail-timeout: 60000  # 初始化失败超时
      connection-init-sql: "SELECT 1"   # 连接初始化验证SQL
      connection-test-query: "SELECT 1" # 连接测试查询
  redis:
    # Redis服务器地址
    host: ${music.redis.host}
    # Redis服务器端口号
    port: ${music.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${music.redis.password}
  jackson:
    serialization:
      # 自动将前端返回的date类型数据转换为时间戳
      write-dates-as-timestamps: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
jwt:
  secret: ${music.jwt.secret}