spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: musicommunity
  datasource:
    url: jdbc:mysql://${music.mysql.ip}:${music.mysql.port}/${music.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${music.mysql.username}
    password: ${music.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    spring:
      datasource:
        hikari:
          minimum-idle: 5                  # 最小空闲连接数
          maximum-pool-size: 15            # 最大连接数
          idle-timeout: 600000             # 连接池中连接最大空闲时间(10分钟)
          max-lifetime: 1800000            # 连接最大生存时间(30分钟，必须小于MySQL wait_timeout)
          connection-timeout: 60000        # 连接超时时间(60秒)
          validation-timeout: 5000         # 连接验证超时时间(5秒)
          initialization-fail-timeout: 60000 # 初始化失败超时
          connection-init-sql: "SELECT 1"  # 连接初始化验证SQL
          connection-test-query: "SELECT 1" # 连接测试查询
          auto-commit: true                # 自动提交
          pool-name: "HikariCP-Pool"       # 连接池名称
          register-mbeans: false           # 是否注册JMX MBeans
          leak-detection-threshold: 60000  # 连接泄漏检测阈值(60秒)
  redis:
    # Redis服务器地址
    host: ${music.redis.host}
    # Redis服务器端口号
    port: ${music.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${music.redis.password}
  jackson:
    serialization:
      # 自动将前端返回的date类型数据转换为时间戳
      write-dates-as-timestamps: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
jwt:
  secret: ${music.jwt.secret}